### ISSUE TITLE
parse error: bad duration syntax for CPU and network

### ISSUE THREAD

**Issue by Elikill58** [rfmoz/grafana-dashboards#116]
For multiple charts, I get the error `bad_data: 1:101: parse error: bad duration syntax: "5m1"` :

![image](https://user-images.githubusercontent.com/17381066/214824671-ebdcf463-6439-472e-aaf6-3a0214e9bf8d.png)

**Comment by teamsmiley** [comment]
same here

**Comment by JannikSommer** [comment]
It seems that changing the `$__rate_interval` to just `$__interval` fixes this issue. However, it may be that the stats no longer reflect the data it is designed to.

**Comment by Elikill58** [comment]
@JannikSommer Yes, I made a PR about this to suggest the change

**Comment by firebird631** [comment]
same here, I've replaced by $__range seems $__interval does not the job

**Comment by Nthalk** [comment]
I've found that this is present with prometheus 2.15.x, and is resolved in at least 2.31, I believe I remember seeing a bug report about this being fixed in 2.25.

The issuer here is that there's an old prometheus that's running.

My particular encounter with this has to do with Ubuntu 20 only having up to 2.15 in the repo, and I have a fixed server running on Ubuntu 22.

There doesn't appear to be a ppa with a more up-to-date prometheus (https://packages.ubuntu.com/search?keywords=prometheus), so a dist upgrade is required.

**Comment by ZhenyaPav** [comment]
I'm having this issue right now, with the latest prometheus available on Ubuntu 22. A lot of panels, mainly related to CPU, network and disk have errors along the lines of `Status: 400. Message: bad_data: parse error at char 125: bad duration syntax: "2m1"`
